### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by jkms** [ihaveamac/wiiu-things#3]
Worked yesterday, broken today...

```
$ python3 wiiu_cdndownload.py xxxxxxxxxxxxx
Downloading TMD (title.tmd)...
Contents: 39
Total size: xxxxxxxxxxxxxxxxxxxxxxxxxx
Writing cert (title.cert)...
Downloading: 00000000.app...  100.0%      65536 /      65536 (0.0625) MiB)
Downloading: 00000001.app...  100.0%      32768 /      32768 (0.03125) MiB)
Downloading: 00000002.app...  100.0%      32768 /      32768 (0.03125) MiB)
Downloading: 00000003.app...  100.0%     196608 /     196608 (0.1875) MiB)
Traceback (most recent call last):
  File "wiiu_cdndownload.py", line 115, in <module>
    download(base + '/' + c[0] + '.h3', True, f, 'Downloading: {}.h3...'.format(c[0]))
  File "wiiu_cdndownload.py", line 48, in download
    cn = urlopen(url)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
Looks like the big N changed something?....

**Comment by ihaveamac** [comment]
It failed downloading an h3 file, I don't know why it would be missing if the tmd says it exists.

**Comment by jkms** [comment]
looks like the server was just having a hiccup? back online now.
