### ISSUE TITLE
ValueError invalid key size (0) for AES

### ISSUE THREAD

**Issue by C0sm1x** [ihaveamac/wiiu-things#6]
When trying to run wiiu_decrypt.py I get this

```
Title ID:               <Not sure if I should display that. The others are blank though>
Encrypted Titlekey:     
Decrypted Titlekey:     
Decrypting 00000000...Traceback (most recent call last):
  File "./wiiu_decrypt.py", line 163, in <module>
    cipher_content = Cipher(algorithms.AES(decrypted_titlekey), modes.CBC(c[1] + bytes(14)), backend=default_backend()).decryptor()
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 35, in __init__
    self.key = _verify_key_size(self, key)
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 21, in _verify_key_size
    len(key) * 8, algorithm.name
ValueError: Invalid key size (0) for AES.
```
I'm assuming it can't find the titlekey? Especially since they are blank at the top.

**Comment by C0sm1x** [comment]
I found the problem. The title.tik file was an html file, not a binary file.

**Comment by DweetOnWeed** [comment]
how did you change it to a binary file
